### PR TITLE
Masco-geocoding: NEW App - Initial

### PR DESCRIPTION
**Pull request by unapped**
Masco-geocoding: NEW App - Initial

#### Please check if your PR fulfills the following requirements:
- [√] Testing of all the changes has been performed (for bug fixes / features)
- [N/A] The manual_readme_content.md has been reviewed and added / updated if needed (for bug fixes / features)
- [√] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [√] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [??] Verify all checks are passing.
- [√] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [√] Do NOT submit updates to dependencies unless it fixes an issue.
## Pull Request Type
NOTE: Branch was / is DEV

#### Please check the type of change your PR introduces:
- [√] New App
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe):

## Security Considerations (REQUIRED)
- [√] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers),
  please document them in the `manual_readme_content.md`.
- [√] If this is a new connector or you are adding new actions
    - [N/A] Please document in the `manual_readme_content.md` all methods (eg, OAuth) used to authenticate
      with the service that the connector is integrating with.
    - [√] If any actions are unable to run on SOAR Cloud, please document this in the `manual_readme_content.md`.
- [NO] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [NO] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [NO] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

## Release Notes (REQUIRED)
- Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.

## What is the current behavior? (OPTIONAL)
- Describe the current behavior that you are modifying.
NEW APP - looks up GPS data such as lat/long and returns street address, also looks up street address and returns lat/long

## What is the new behavior? (OPTIONAL)
- Describe the behavior or changes that are being added by this PR.
NEW APP - looks up GPS data such as lat/long and returns street address, also looks up street address and returns lat/long

## Other information (OPTIONAL)
- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.
NEW APP - looks up GPS data such as lat/long and returns street address, also looks up street address and returns lat/long

## Pay close attention to (OPTIONAL)
- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.
NEW APP - looks up GPS data such as lat/long and returns street address, also looks up street address and returns lat/long

## Screenshots (if relevant)

---
Thanks for contributing!
Cheers!

### CODE REVIEW

**Comment by unapped** [comment]
I have cleared out the errors and now the only ones that remain have the verbose text
                        "Test execution failed. The Phantom team will resolve this issue"
or relate to service ports that are not used in the app
Please advise what I can do to help clear this up. I have two more apps that I want to upload but am waiting till I get one resolved so I can do a better job the second time round. 
Thank you.

**Comment by stutib-crest** [comment]
Hi @unapped ,
We notices that the app's geocodingmapsco.json does not contain an app id. Could you please generate an appid and update the same.

**Comment by unapped** [comment]
added appid to json as per instruction. thank you

**Comment by stutib-crest** [comment]
Hi @unapped ,
The publisher field in the geocodingmapsco.json is "Unapproved". Could you please update this with the name of the person or the organisation publishing this app.
Also please verify the changes done by us as part of our developer checklist where we have also update the logo for dark theme.
Thanks.

**Review by mmomin-crest — DISMISSED** [review]

**Comment by stutib-crest** [comment]
Hi @unapped ,
For the logo files, the naming convention requires the format logo_<connector_name>.svg, which is why we updated the file names. Additionally, we modified the background of the logo for the dark theme, as the previous black background did not  contrast well. Would you prefer to keep the original design for the dark theme logo, or the updated version by us?

**Comment by unapped** [comment]
> Hi @unapped , For the logo files, the naming convention requires the format logo_<connector_name>.svg, which is why we updated the file names. Additionally, we modified the background of the logo for the dark theme, as the previous black background did not contrast well. Would you prefer to keep the original design for the dark theme logo, or the updated version by us?

the updated version by you - give me a min and ill look at it right away

**Comment by unapped** [comment]
> Hi @unapped , For the logo files, the naming convention requires the format logo_<connector_name>.svg, which is why we updated the file names. Additionally, we modified the background of the logo for the dark theme, as the previous black background did not contrast well. Would you prefer to keep the original design for the dark theme logo, or the updated version by us?

I just checked the JSON and its updated…
    "logo": "logo_geocodingmapsco.svg",
    "logo_dark": "logo_geocodingmapsco_dark.svg",
and the file names are yours...
I see, I must have accidentally put back in my old ones, let me remove them

**Review by mmomin-crest — APPROVED** [review]

**Comment by unapped** [comment]
@stutib-crest any chance you could join the reviewers / approvers list?
once this one is through I will use it to template the next one. I have certainly learnt a bit about the development and commit process.
TIA

**Comment by stutib-crest** [comment]
> @stutib-crest any chance you could join the reviewers / approvers list? once this one is through I will use it to template the next one. I have certainly learnt a bit about the development and commit process. TIA

Hello @unapped ,
As I have added changes to the PR, I cannot review or approve it. We are working on this PR and will release it soon.
Thanks

**Comment by unapped** [comment]
@stutib-crest thanks for the info.
Hopefully I can take the learnings from this one to the next and you dont have to do half as much to help with success

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
